[package]
name = "brainfuck"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.20.0"
structopt = "0.3.22"
thiserror = "1.0.31"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
